# Generated by Django 6.0.7 on 2026-09-10 06:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(db_index=True, max_length=30, unique=True, verbose_name='Numero ordine')),
                ('email', models.EmailField(help_text='Email del cliente — richiesta anche per ordini guest.', max_length=254, verbose_name='Email')),
                ('status', models.CharField(choices=[('pending', 'In attesa di pagamento'), ('paid', 'Pagato'), ('processing', 'In lavorazione'), ('shipped', 'Spedito'), ('delivered', 'Consegnato'), ('cancelled', 'Annullato'), ('refunded', 'Rimborsato')], db_index=True, default='pending', max_length=20, verbose_name='Stato')),
                ('shipping_first_name', models.CharField(max_length=100, verbose_name='Nome spedizione')),
                ('shipping_last_name', models.CharField(max_length=100, verbose_name='Cognome spedizione')),
                ('shipping_line1', models.CharField(max_length=255, verbose_name='Indirizzo spedizione 1')),
                ('shipping_line2', models.CharField(blank=True, max_length=255, verbose_name='Indirizzo spedizione 2')),
                ('shipping_city', models.CharField(max_length=100, verbose_name='Città spedizione')),
                ('shipping_province', models.CharField(max_length=10, verbose_name='Provincia spedizione')),
                ('shipping_postal_code', models.CharField(max_length=10, verbose_name='CAP spedizione')),
                ('shipping_country', models.CharField(default='IT', max_length=2, verbose_name='Paese spedizione')),
                ('billing_first_name', models.CharField(blank=True, max_length=100, verbose_name='Nome fatturazione')),
                ('billing_last_name', models.CharField(blank=True, max_length=100, verbose_name='Cognome fatturazione')),
                ('billing_line1', models.CharField(blank=True, max_length=255, verbose_name='Indirizzo fatturazione 1')),
                ('billing_line2', models.CharField(blank=True, max_length=255, verbose_name='Indirizzo fatturazione 2')),
                ('billing_city', models.CharField(blank=True, max_length=100, verbose_name='Città fatturazione')),
                ('billing_province', models.CharField(blank=True, max_length=10, verbose_name='Provincia fatturazione')),
                ('billing_postal_code', models.CharField(blank=True, max_length=10, verbose_name='CAP fatturazione')),
                ('billing_country', models.CharField(default='IT', max_length=2, verbose_name='Paese fatturazione')),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Subtotale')),
                ('shipping_cost', models.DecimalField(decimal_places=2, default='0.00', max_digits=10, verbose_name='Costo spedizione')),
                ('total', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Totale')),
                ('stripe_payment_intent_id', models.CharField(blank=True, db_index=True, max_length=255, verbose_name='Stripe PaymentIntent ID')),
                ('notes', models.TextField(blank=True, verbose_name='Note del cliente')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creato il')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Aggiornato il')),
                ('user', models.ForeignKey(blank=True, help_text='Null per ordini guest (PRD §3.2 Gift Buyer).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='Utente')),
            ],
            options={
                'verbose_name': 'Ordine',
                'verbose_name_plural': 'Ordini',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200, verbose_name='Nome prodotto')),
                ('variant_metal', models.CharField(max_length=20, verbose_name='Metallo')),
                ('variant_metal_display', models.CharField(max_length=50, verbose_name='Metallo (display)')),
                ('variant_size', models.CharField(max_length=20, verbose_name='Misura')),
                ('sku', models.CharField(max_length=50, verbose_name='SKU')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Prezzo unitario')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Quantità')),
                ('line_total', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Totale riga')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order', verbose_name='Ordine')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='catalog.productvariant', verbose_name='Variante')),
            ],
            options={
                'verbose_name': 'Articolo ordine',
                'verbose_name_plural': 'Articoli ordine',
            },
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['user', 'status'], name='orders_orde_user_id_02a211_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['created_at'], name='orders_orde_created_0e92de_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['email'], name='orders_orde_email_88c705_idx'),
        ),
    ]
