# Generated by Django 5.1.15 on 2026-09-02 16:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Nome')),
                ('last_name', models.CharField(max_length=100, verbose_name='Cognome')),
                ('line1', models.CharField(max_length=255, verbose_name='Indirizzo riga 1')),
                ('line2', models.CharField(blank=True, max_length=255, verbose_name='Indirizzo riga 2')),
                ('city', models.CharField(max_length=100, verbose_name='Città')),
                ('province', models.CharField(help_text='Sigla provincia (es. MI, RM, TO)', max_length=10, verbose_name='Provincia')),
                ('postal_code', models.CharField(max_length=10, verbose_name='CAP')),
                ('country', models.CharField(default='IT', max_length=2, verbose_name='Paese')),
                ('is_default', models.BooleanField(default=False, verbose_name='Indirizzo predefinito')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creato il')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Aggiornato il')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to=settings.AUTH_USER_MODEL, verbose_name='Utente')),
            ],
            options={
                'verbose_name': 'Indirizzo',
                'verbose_name_plural': 'Indirizzi',
                'ordering': ['-is_default', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CustomerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, help_text='Es. +39 02 1234567', max_length=20, verbose_name='Telefono')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='Data di nascita')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creato il')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Aggiornato il')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='Utente')),
            ],
            options={
                'verbose_name': 'Profilo cliente',
                'verbose_name_plural': 'Profili clienti',
            },
        ),
    ]
