# Generated by Django 5.1.15 on 2026-09-02 16:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(blank=True, db_index=True, help_text='Per carrelli di utenti non registrati.', max_length=40, null=True, verbose_name='Chiave sessione')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creato il')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Aggiornato il')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='carts', to=settings.AUTH_USER_MODEL, verbose_name='Utente')),
            ],
            options={
                'verbose_name': 'Carrello',
                'verbose_name_plural': 'Carrelli',
            },
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Quantità')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creato il')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Aggiornato il')),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='cart.cart', verbose_name='Carrello')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cart_items', to='catalog.productvariant', verbose_name='Variante')),
            ],
            options={
                'verbose_name': 'Articolo nel carrello',
                'verbose_name_plural': 'Articoli nel carrello',
                'unique_together': {('cart', 'variant')},
            },
        ),
        migrations.CreateModel(
            name='StockReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(verbose_name='Quantità riservata')),
                ('expires_at', models.DateTimeField(db_index=True, verbose_name='Scade il')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Attiva')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creato il')),
                ('cart_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='cart.cartitem', verbose_name='Articolo carrello')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='catalog.productvariant', verbose_name='Variante')),
            ],
            options={
                'verbose_name': 'Riserva stock',
                'verbose_name_plural': 'Riserve stock',
                'indexes': [models.Index(fields=['is_active', 'expires_at'], name='cart_stockr_is_acti_8f31b3_idx')],
            },
        ),
    ]
