# Generated by Django 6.0.7 on 2026-09-10 06:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessedWebhookEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_event_id', models.CharField(db_index=True, max_length=255, unique=True, verbose_name='Stripe Event ID')),
                ('event_type', models.CharField(help_text='Es. payment_intent.succeeded', max_length=100, verbose_name='Tipo evento')),
                ('processed_at', models.DateTimeField(auto_now_add=True, verbose_name='Elaborato il')),
            ],
            options={
                'verbose_name': 'Evento webhook elaborato',
                'verbose_name_plural': 'Eventi webhook elaborati',
                'ordering': ['-processed_at'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_payment_intent_id', models.CharField(db_index=True, max_length=255, unique=True, verbose_name='Stripe PaymentIntent ID')),
                ('stripe_charge_id', models.CharField(blank=True, max_length=255, verbose_name='Stripe Charge ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Importo')),
                ('currency', models.CharField(default='EUR', max_length=3, verbose_name='Valuta')),
                ('status', models.CharField(choices=[('pending', 'In attesa'), ('succeeded', 'Riuscito'), ('failed', 'Fallito'), ('refunded', 'Rimborsato')], db_index=True, default='pending', max_length=20, verbose_name='Stato')),
                ('idempotency_key', models.CharField(help_text='Chiave usata per creare il PaymentIntent su Stripe.', max_length=255, unique=True, verbose_name='Chiave idempotenza')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creato il')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Aggiornato il')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='orders.order', verbose_name='Ordine')),
            ],
            options={
                'verbose_name': 'Pagamento',
                'verbose_name_plural': 'Pagamenti',
                'ordering': ['-created_at'],
            },
        ),
    ]
