# Generated by Django 6.0.7 on 2026-09-10 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(db_index=True, max_length=30, unique=True, verbose_name='Numero fattura')),
                ('fattura24_id', models.CharField(blank=True, help_text='ID esterno assegnato da Fattura24.', max_length=255, verbose_name='Fattura24 ID')),
                ('status', models.CharField(choices=[('pending', 'In attesa'), ('submitted', 'Inviata'), ('accepted', 'Accettata'), ('rejected', 'Rifiutata'), ('error', 'Errore')], db_index=True, default='pending', max_length=20, verbose_name='Stato')),
                ('pdf_url', models.URLField(blank=True, help_text='Link al PDF generato della fattura.', verbose_name='URL PDF')),
                ('xml_content', models.TextField(blank=True, help_text='XML SDI-compliant (archiviato per audit).', verbose_name='Contenuto XML')),
                ('error_message', models.TextField(blank=True, verbose_name='Messaggio di errore')),
                ('attempts', models.PositiveIntegerField(default=0, help_text='Numero di tentativi di invio.', verbose_name='Tentativi')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creato il')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Aggiornato il')),
            ],
            options={
                'verbose_name': 'Fattura',
                'verbose_name_plural': 'Fatture',
                'ordering': ['-created_at'],
            },
        ),
    ]
