# Generated by Django 6.0.7 on 2026-09-10 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewsletterSubscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True, verbose_name='Email')),
                ('is_active', models.BooleanField(default=True, help_text="Disattivato quando l'utente annulla l'iscrizione.", verbose_name='Attivo')),
                ('subscribed_at', models.DateTimeField(auto_now_add=True, verbose_name='Iscritto il')),
                ('unsubscribed_at', models.DateTimeField(blank=True, null=True, verbose_name='Disiscritto il')),
            ],
            options={
                'verbose_name': 'Iscritto newsletter',
                'verbose_name_plural': 'Iscritti newsletter',
                'ordering': ['-subscribed_at'],
            },
        ),
    ]
