# Generated by Django 5.1.15 on 2026-09-02 16:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('slug', models.SlugField(max_length=120, unique=True, verbose_name='Slug')),
                ('description', models.TextField(blank=True, verbose_name='Descrizione')),
                ('image', models.ImageField(blank=True, null=True, upload_to='categories/', verbose_name='Immagine')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Attiva')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Ordine')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creato il')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Aggiornato il')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='catalog.category', verbose_name='Categoria padre')),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorie',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nome')),
                ('slug', models.SlugField(max_length=220, unique=True, verbose_name='Slug')),
                ('description', models.TextField(blank=True, verbose_name='Descrizione')),
                ('base_price', models.DecimalField(decimal_places=2, help_text='Prezzo di listino in EUR. Le varianti possono sovrascriverlo.', max_digits=10, verbose_name='Prezzo base')),
                ('metal', models.CharField(choices=[('gold', 'Oro 18K'), ('rose', 'Oro Rosa'), ('silver', 'Argento 925')], default='gold', max_length=20, verbose_name='Metallo predefinito')),
                ('gem', models.CharField(blank=True, choices=[('diamond', 'Diamante'), ('emerald', 'Smeraldo'), ('ruby', 'Rubino'), ('sapphire', 'Zaffiro'), ('amethyst', 'Ametista'), ('none', 'Nessuna')], default='none', max_length=20, verbose_name='Pietra')),
                ('purity', models.CharField(default='18K', help_text='Es. 18K, 925, etc.', max_length=20, verbose_name='Purezza')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Attivo')),
                ('is_featured', models.BooleanField(db_index=True, default=False, verbose_name='In evidenza')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creato il')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Aggiornato il')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='catalog.category', verbose_name='Categoria')),
            ],
            options={
                'verbose_name': 'Prodotto',
                'verbose_name_plural': 'Prodotti',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='Foto principale (1:1, soggetto centrato).', upload_to='products/', verbose_name='Immagine principale')),
                ('image_alt', models.ImageField(blank=True, help_text='Seconda foto per hover-swap (stesso formato 1:1).', null=True, upload_to='products/', verbose_name='Immagine alternativa (hover)')),
                ('alt_text', models.CharField(blank=True, help_text='Descrizione per accessibilità.', max_length=200, verbose_name='Testo alternativo')),
                ('is_primary', models.BooleanField(default=False, verbose_name='Immagine principale')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Ordine')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creato il')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='catalog.product', verbose_name='Prodotto')),
            ],
            options={
                'verbose_name': 'Immagine prodotto',
                'verbose_name_plural': 'Immagini prodotto',
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metal', models.CharField(choices=[('gold', 'Oro 18K'), ('rose', 'Oro Rosa'), ('silver', 'Argento 925')], max_length=20, verbose_name='Metallo')),
                ('size', models.CharField(help_text='Es. 50, 52, 54 per anelli; Unica per collane.', max_length=20, verbose_name='Misura')),
                ('sku', models.CharField(db_index=True, max_length=50, unique=True, verbose_name='SKU')),
                ('price_override', models.DecimalField(blank=True, decimal_places=2, help_text='Se impostato, sovrascrive il prezzo base del prodotto.', max_digits=10, null=True, verbose_name='Prezzo personalizzato')),
                ('stock_quantity', models.PositiveIntegerField(default=0, verbose_name='Quantità in stock')),
                ('reserved_quantity', models.PositiveIntegerField(default=0, help_text='Stock riservato da carrelli attivi (gestito da cart/services.py).', verbose_name='Quantità riservata')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Attiva')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creato il')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Aggiornato il')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='catalog.product', verbose_name='Prodotto')),
            ],
            options={
                'verbose_name': 'Variante',
                'verbose_name_plural': 'Varianti',
                'ordering': ['metal', 'size'],
            },
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['category', 'is_active'], name='catalog_pro_categor_891fe8_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['metal', 'is_active'], name='catalog_pro_metal_3eaa6c_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['is_featured', 'is_active'], name='catalog_pro_is_feat_b968c0_idx'),
        ),
        migrations.AddIndex(
            model_name='productvariant',
            index=models.Index(fields=['product', 'is_active'], name='catalog_pro_product_6c5ee9_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='productvariant',
            unique_together={('product', 'metal', 'size')},
        ),
    ]
